spring.application.name=iot-service
server.port=8080

spring.r2dbc.url=r2dbc:mysql://localhost:3306/greenhouse_db
spring.r2dbc.username=root
spring.r2dbc.password=kvn2004

jwt.secret=bcd5bcc8555ca7d9f7cf971aecd33dc631a3b61bef110dcc2ba3634d4aaaf93d
jwt.access.expiration=900000
jwt.refresh.expiration=604800000